#!/usr/bin/env bash
#
# pull-toolkit.sh — Pulls .github/ and .vscode/ from copilot-agent-toolkit
# into the current repository.
#
# Usage:
#   ./scripts/pull-toolkit.sh [--ref <branch|tag|sha>] [--path <dir>] [--dry-run]
#
# One-liner for a fresh repo:
#   curl -sSL https://raw.githubusercontent.com/onsenturk/copilot-agent-toolkit/main/scripts/pull-toolkit.sh | bash
#
# Set GITHUB_TOKEN to avoid the unauthenticated GitHub API rate limit.
#
# Requires: bash, curl, jq

set -euo pipefail

OWNER="onsenturk"
REPO="copilot-agent-toolkit"
FOLDERS=(".github" ".vscode")

REF="main"
TARGET_PATH="$(pwd)"
DRY_RUN=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ref)     REF="$2"; shift 2 ;;
    --path)    TARGET_PATH="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    -h|--help)
      sed -n '2,18p' "$0"
      exit 0
      ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
done

if ! command -v jq >/dev/null 2>&1; then
  echo "[fail] jq is required (install via 'brew install jq' or 'apt install jq')." >&2
  exit 1
fi

API_ROOT="https://api.github.com/repos/${OWNER}/${REPO}"
RAW_ROOT="https://raw.githubusercontent.com/${OWNER}/${REPO}/${REF}"

CURL_AUTH=()
if [[ -n "${GITHUB_TOKEN:-}" ]]; then
  CURL_AUTH=(-H "Authorization: Bearer ${GITHUB_TOKEN}")
fi

api() {
  curl -fsSL -H 'Accept: application/vnd.github+json' -H 'User-Agent: pull-toolkit.sh' \
    "${CURL_AUTH[@]}" "$1"
}

# Recursively list files under a folder at $REF; emits one path per line.
list_tree() {
  local folder="$1"
  local entries
  if ! entries=$(api "${API_ROOT}/contents/${folder}?ref=${REF}" 2>/dev/null); then
    echo "[warn] ${folder} not found at ref '${REF}' — skipping." >&2
    return 0
  fi

  local count
  count=$(echo "$entries" | jq 'length')
  for ((i = 0; i < count; i++)); do
    local type path
    type=$(echo "$entries" | jq -r ".[$i].type")
    path=$(echo "$entries" | jq -r ".[$i].path")
    if [[ "$type" == "file" ]]; then
      echo "$path"
    elif [[ "$type" == "dir" ]]; then
      list_tree "$path"
    fi
  done
}

resolve_sha() {
  api "${API_ROOT}/commits/${REF}" | jq -r '.sha'
}

# ---------- main ----------

SHA=$(resolve_sha)
echo "[i] Pulling ${OWNER}/${REPO} @ ${SHA:0:7} (${REF})"
echo "[i] Target: ${TARGET_PATH}"
$DRY_RUN && echo "[i] DRY-RUN: no files will be written"

TOTAL=0
for folder in "${FOLDERS[@]}"; do
  echo
  echo "=== ${folder} ==="
  while IFS= read -r filepath; do
    [[ -z "$filepath" ]] && continue
    target="${TARGET_PATH}/${filepath}"

    if $DRY_RUN; then
      echo "  [dry-run] ${filepath}"
      TOTAL=$((TOTAL + 1))
      continue
    fi

    mkdir -p "$(dirname "$target")"
    if curl -fsSL "${CURL_AUTH[@]}" -o "$target" "${RAW_ROOT}/${filepath}"; then
      echo "  [ok] ${filepath}"
      TOTAL=$((TOTAL + 1))
    else
      echo "  [fail] ${filepath}" >&2
    fi
  done < <(list_tree "$folder")
done

if ! $DRY_RUN; then
  version_file="${TARGET_PATH}/.github/.toolkit-version"
  cat > "$version_file" <<EOF
# Auto-generated by pull-toolkit.sh — do not edit manually.
upstream_repo: ${OWNER}/${REPO}
upstream_ref:  ${REF}
upstream_sha:  ${SHA}
pulled_at:     $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
  echo
  echo "[i] Wrote ${version_file}"
fi

echo
echo "[done] ${TOTAL} file(s) processed."
